const mongoose = require('mongoose');

const payoutSchema = new mongoose.Schema({
  claimId: {
    type: String,
    required: true,
    unique: true
  },
  userId: {
    type: String,
    required: true
  },
  payoutId: {
    type: String,
    required: false // Generated by Stripe Payout (or simulated)
  },
  amount: {
    type: Number,
    required: true
  },
  status: {
    type: String,
    enum: ['PENDING', 'SUCCESS', 'FAILED'],
    default: 'PENDING'
  }
}, { timestamps: true });

module.exports = mongoose.model('Payout', payoutSchema);
